"""add location field to applications model

Revision ID: 8abb0b1db29d
Revises: e055bab5df59
Create Date: 2026-02-16 21:56:10.744207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abb0b1db29d'
down_revision = 'e055bab5df59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_applications', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
