"""Inadded licence number field to doctors model

Revision ID: 9554e57c3ea9
Revises: be8890f30f19
Create Date: 2026-01-22 17:26:50.864412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9554e57c3ea9'
down_revision = 'be8890f30f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicalLicenceNumber', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('medicalLicenceNumber')

    # ### end Alembic commands ###
